package com.mridul.studyfocus;

import android.app.*;import android.content.*;import android.content.pm.*;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;

public class AppPickerActivity extends Activity {
    LinearLayout list; Set<String> selected=new HashSet<>();
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(11,15,13));getWindow().setNavigationBarColor(Color.rgb(11,15,13));selected.addAll(getSharedPreferences("block",0).getStringSet("apps",Collections.emptySet()));ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(20,24,20,24);sc.addView(list);TextView h=new TextView(this);h.setText("Apps blocked during Focus Mode");h.setTextColor(Color.WHITE);h.setTextSize(25);h.setPadding(0,0,0,8);list.addView(h);TextView p=new TextView(this);p.setText("Choose distracting apps. They will be covered while a focus session is active.");p.setTextColor(Color.LTGRAY);p.setTextSize(15);list.addView(p);Button save=new Button(this);save.setText("Save");save.setOnClickListener(v->{getSharedPreferences("block",0).edit().putStringSet("apps",new HashSet<>(selected)).apply();finish();});list.addView(save);addApps();setContentView(sc);}
    void addApps(){PackageManager pm=getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> apps=pm.queryIntentActivities(q,0);Collections.sort(apps,(a,b)->a.loadLabel(pm).toString().compareToIgnoreCase(b.loadLabel(pm).toString()));for(ResolveInfo r:apps){String pkg=r.activityInfo.packageName;if(pkg.equals(getPackageName()))continue;CheckBox c=new CheckBox(this);c.setText(r.loadLabel(pm));c.setTextColor(Color.WHITE);c.setTextSize(16);c.setCompoundDrawablesWithIntrinsicBounds(r.loadIcon(pm),null,null,null);c.setPadding(0,10,0,10);c.setChecked(selected.contains(pkg));c.setOnCheckedChangeListener((v,on)->{if(on)selected.add(pkg);else selected.remove(pkg);});list.addView(c);}}
}
